### PR TITLE
updated Game#rack specs with many comments

### PR DESCRIPTION
**Pull request by jmks**
Hey Vince

I added a couple simple tests about `Game#rack` method. I also left (big!) comments about a couple of the tests.

One test is failing, showing that the `@rack` instance variable gets altered by the `rack` method. The test itself is bad but does demonstrate the problem.

It would be good to first get this test passing. The test should then be replaced with something that uses a `Game` public method to determine if it changed. A game would usually have a way to determine its state, but maybe something like `inspect` would do.

### CODE REVIEW

**Comment by VincentLu91** [comment]
I just merged. Are you able to come to the Brigade social tomorrow so we can get the test passing? I know I've been asking for a lot, but I hope that some guidance could help. I'm looking at the test to see how to demonstrate whether the @rack instance variable is mutated or not. I'll look into the inspect method as well! 

Thanks Jason! Some lessons learned.

**Comment by VincentLu91** [comment]
I've been looking at the test and the code. Looking at line 75 of game_spec.rb, I still don't know how or why we get this:

got: "[[\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"], [\"-\", \"-\", \"-\", \"-\", \"-\", \"-\"]]"

This is what got the test to fail. Not sure how come we got the \"-\"s.

**Comment by jmks** [comment]
Don't be too distracted by all the `\"`s. It's printing a string (from inspect) that contains many double-quote characters, so it escapes them with `\` to mean a literal double-quote.

The test indicates the `@rack` variable has changed after calling the `rack` method. Afterwards it seems to contain a whole bunch of dashes. I'm sure you can find where that's happening, but the problem is the why.

**Comment by VincentLu91** [comment]
I tried removing the inspect methods from line 75. And the tests pass. I think the inspect method makes the difference because you want to know the actual value is in str. 

If I'm right, I think that :instance_variable_get is used to get the value of the instance value @ rack. I'm not quite clear on the send method though.

**Comment by jmks** [comment]
Hi Vince,

I setup the test so that it fails because of an error in the code, and you should only have to edit the `rack` method to get it to pass. 

The actual test implementation isn't good, but it works. For reference, `instance_variable_get` does retrieve an instance variable on the receiver. It's kind of a hacky thing to do because you are breaking encapsulation, a core idea behind OOP.

The `send` method, and the closely related `public_send`, are fundamental Ruby methods for objects. In Ruby, you send objects methods, rather than invoking methods, like in other languages. Every method you call actually sends the object a message and arguments. For instance, `"somestring".split("s")` is actually interpreted as `somestring.send(:split, "s")`. You send a string the :split message with argument "s". I don't know why I used `send` there, using `@game.instance_variable_get(:"@rack")` would have worked just fine.

**Comment by VincentLu91** [comment]
I think i'm beginning to understand what this is about, I saw your clue:

# the rack is initially empty

```
  # [3] pry(#<Game>):1> @rack
  # => [[], [], [], [], [], [], []]

  # and rack prints empty
  # [4] pry(#<Game>):1> rack
  # => ["------", "------", "------", "------", "------", "------", "------"]
```

the array value, for the @rack variable, is [[], [], [], [], [], [], []]
But if you print it, the little empty arrays [] should be in string form instead "------"

I'm not exactly sure how to do that. The original rack gives [["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"], ["-", "-", "-", "-", "-", "-"]] instead of ["------", "------", "------", "------", "------", "------", "------"]

**Comment by jmks** [comment]
Yeah, I think you're getting closer.

Don't conflate the `@rack` variable and the `rack` method. They are separate things with different responsibilities.

Think about what the `rack` method should be doing. It's just printing a convenient representation of the `@rack` variable, which is the game board. So the method is printing the game board for human eyes, while the variable is holding the actual game board for game processing.

It's easiest to visualize the problem with the pry session I included:

```
[3] pry(#<Game>):1> @rack
 => [[], [], [], [], [], [], []]

[4] pry(#<Game>):1> rack
=> ["------", "------", "------", "------", "------", "------", "------"]

[5] pry(#<Game>):1> @rack
=> [["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"],
      ["-", "-", "-", "-", "-", "-"]]
```

When the game is new the variable is an array of empty arrays (several columns of empty rows) since there are no pieces in play. We wanted to visualize emptiness as dashes when printed, so the method returns an array of columns of dashes. But when we check variable again, it's got all these dash things in them. 

What do those dashes have to do with the game? What would happen if someone tried to add a disc to a column now?

**Comment by VincentLu91** [comment]
I'm really not sure how to do that. @rack is the actual game board variable containing the actual values (in this ways, an array of sub-array of dashes) whereas the rack method prints the graphical representation of the game board variable (i.e. array of strings).

Honestly, I don't know the best way to do that. I tried doing this:
def rack
    @rack.map { |col| col.concat(["-"] \* (6 - col.length)) }
         .map { |col| col.join }
    @rack.each do |x|
         x.to_s
    end
end

I know this is wrong, because I shouldn't be changing the @ rack instance variable. But what should I do? Create a copy of the instance variable and then convert the sub-arrays to strings?

**Comment by jmks** [comment]
> I shouldn't be changing the @ rack instance variable

That is exactly the problem. The `@rack` variable is changed by our initial call to `rack`. It adds a bunch of dashes to `@rack` that shouldn't be there and could break the game.

> Create a copy of the instance variable

Sounds like a good plan :+1: 

But be careful when you make the copy. You'll have to make a copy of the right object. `Object#dup` creates a shallow copy so copies any references the instance uses. That is important for `@rack` as it is an array of arrays.

**Comment by VincentLu91** [comment]
do I make a deep copy or a shallow copy? Deep copy is useful for creating a separate object that looks identical to the original, but less risky as you're not modifying the original object via references.

**Comment by jmks** [comment]
You could do either, depending on what you are cloning. If you clone the whole `@rack` object you would need a deep copy (since its elements are arrays), but if you cloned the columns (which will only contain strings) you could do a shallow copy.

There also isn't a default deep copy method in Ruby. You can usually get by using `Marshal.load(Marshal.dump(@object))` if the object is "simple" enough, but there are at least two methods for shallow copying.

**Comment by VincentLu91** [comment]
def rack
    the_rack = @rack.dup
    the_rack.map { |col| col.concat(["-"] \* (6 - col.length)) }
         .map { |col| col.join }
  end

For the first line in the method, I tried both @ rack.dup and @rack .clone and they both give the same failure.

Maybe I'll try Marshalling, not sure if this works on arrays though...

**Comment by VincentLu91** [comment]
it passes! I'll commit and merge it!

**Comment by jmks** [comment]
Good job!

An alternative was to call `dup` on the `@rack`'s columns just before we started mutating them.

**Pull request merged**
